package web

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"knomit/internal/config"
	"knomit/internal/repos"
)

// newIndexTestServer brings up a real Manager (NOT DisableBackgroundSync — see
// the note on TestRepoIndexEvents_StartupHealEmitsIndexingThenReady) with one
// created repo, returning the router and the repo's instance.
func newIndexTestServer(t *testing.T, repo string) (http.Handler, *repos.RepoInstance) {
	t.Helper()
	home := t.TempDir()
	m := repos.New(context.Background(), repos.Deps{
		Cfg:         config.Config{Home: home},
		AgentBranch: "machine/test",
	})
	if err := m.Start(); err != nil {
		t.Fatalf("start manager: %v", err)
	}
	t.Cleanup(func() { _ = m.Close() })

	s := &Server{Manager: m}
	r := s.NewAPIRouter()
	createViaAPI(t, r, repo)

	ri := m.Get(repo)
	if ri == nil {
		t.Fatalf("repo %s missing after create", repo)
	}
	// createViaAPI waits for the create job, which waits for the heal, so the
	// repo starts every test below in a genuinely terminal state. A test that
	// began mid-heal would be racing the thing it asserts about.
	if state, _, _ := ri.IndexStatus(); state != "ready" {
		t.Fatalf("repo %s is %q after create, want ready", repo, state)
	}
	return r, ri
}

func postRebuild(t *testing.T, r http.Handler, repo string) *httptest.ResponseRecorder {
	t.Helper()
	rec := httptest.NewRecorder()
	r.ServeHTTP(rec, httptest.NewRequest(http.MethodPost,
		"/repos/"+repo+"/branches/machine:test/index-rebuilds", nil))
	return rec
}

// A MANUAL REBUILD MARKS THE INDEX, which it did not do before: the endpoint
// called Rebuild directly and IndexStatus read "ready" for the whole of one, so
// the chip, the REST payload and the event stream all said the index was ready
// while it was being rebuilt.
//
// WHAT THE ASSERTION PROVES, precisely: the state is entered BEFORE the
// rebuild's first task event and left only at its terminal, because both frames
// are generated by publishIndex reading IndexStatus() at the mark. It is not a
// mid-flight sample — blocking Rebuild to take one would need a seam in
// production code that exists for no other reason, and the ordering the marks
// impose is what the UI actually consumes.
func TestRebuild_MarksIndexingThenReady(t *testing.T) {
	r, ri := newIndexTestServer(t, "alpha")

	rec, stop := openIndexStream(t, r)
	defer stop()

	resp := postRebuild(t, r, "alpha")
	if resp.Code != http.StatusCreated {
		t.Fatalf("POST rebuild: got %d, want 201\nbody: %s", resp.Code, resp.Body.String())
	}

	body := rec.waitFor(t, "a terminal index frame", func(b string) bool {
		for _, e := range indexFrames(t, b) {
			if e.Repo == "alpha" && (e.State == "ready" || e.State == "error") {
				return true
			}
		}
		return false
	})

	var mine []repos.IndexEvent
	for _, e := range indexFrames(t, body) {
		if e.Repo == "alpha" {
			mine = append(mine, e)
		}
	}
	got := states(mine)
	if len(got) < 2 || got[0] != "indexing" || got[len(got)-1] != "ready" {
		t.Fatalf("state sequence = %v, want indexing … ready\nbody:\n%s", got, body)
	}

	// The REST view agrees once it is over. Without this the test would pass
	// against an event stream that reports states the endpoint contradicts.
	if state, _, _ := ri.IndexStatus(); state != "ready" {
		t.Fatalf("IndexStatus after rebuild = %q, want ready", state)
	}
}

// THE 409, AND THE REFUSAL'S SILENCE. A rebuild requested while the index is
// already being built is refused, because the rebuild's marks would make it a
// second writer of a cell with no owner — and the create job INFERS from that
// cell, so a rebuild finishing first would make a create report done/100% over
// a half-built index.
//
// Deterministic by SEAM, not by timing: TestMarkIndexing drives the same
// production mutator the startup heal calls, so the state the handler reads is
// the real one, reached the real way. Racing a real heal would test the race.
//
// It asserts SILENCE as well as the status. A refused request that still marked
// would publish frames and move the state — the exact corruption the 409 exists
// to prevent — and a status-code-only test would pass against it.
func TestRebuild_RefusedWhileIndexing_AndMarksNothing(t *testing.T) {
	r, ri := newIndexTestServer(t, "alpha")

	// Enter indexing with KNOWN progress, standing in for a heal in flight.
	ri.TestMarkIndexing()
	ri.TestSetIndexProgress(3, 7)

	// Attach only now, so every frame the stream sees is one this request
	// caused. Frames from the setup above are not in the baseline.
	rec, stop := openIndexStream(t, r)
	defer stop()

	resp := postRebuild(t, r, "alpha")
	if resp.Code != http.StatusConflict {
		t.Fatalf("POST rebuild while indexing: got %d, want 409\nbody: %s", resp.Code, resp.Body.String())
	}

	var problem struct {
		Title  string `json:"title"`
		Detail string `json:"detail"`
	}
	if err := json.Unmarshal(resp.Body.Bytes(), &problem); err != nil {
		t.Fatalf("409 body is not JSON: %v (%s)", err, resp.Body.String())
	}
	// The title discriminates this refusal from hub.Start's "Job already
	// running" 409. Without it the test would pass on the wrong conflict.
	if problem.Title != "Index is busy" {
		t.Fatalf("409 title = %q, want %q (wrong conflict fired)", problem.Title, "Index is busy")
	}
	// The body must name the state and say it is temporary: after a restart a
	// heal on a large repo 409s every rebuild click for minutes, and a bare
	// refusal reads as a broken button.
	if !strings.Contains(problem.Detail, "indexing") {
		t.Errorf("409 detail does not name the current state: %q", problem.Detail)
	}
	if !strings.Contains(problem.Detail, "temporary") {
		t.Errorf("409 detail does not say the condition is temporary: %q", problem.Detail)
	}

	// NOTHING MOVED. Same state, same counts — the refused request did not
	// reach a mark.
	state, done, total := ri.IndexStatus()
	if state != "indexing" || done != 3 || total != 7 {
		t.Fatalf("IndexStatus = (%q, %d, %d), want (indexing, 3, 7) — the refused request marked", state, done, total)
	}

	// And NO index frames were emitted by it. Checked after the state
	// assertions so a failure names the cause before the symptom.
	if frames := indexFrames(t, rec.body()); len(frames) != 0 {
		t.Fatalf("refused rebuild emitted %d index frames, want 0: %+v", len(frames), frames)
	}
}

// A SECOND REBUILD IS STILL THE HUB'S 409, not this one. The two refusals are
// different conflicts on the same status code, and this pins which is which:
// concurrent rebuilds were already excluded by hub.Start's per-op single-flight
// before this change, and that must stay the reason, because the check here
// runs in the handler while the mark runs inside the task fn — so for two
// rebuilds the loser never reaches a mark at all.
func TestRebuild_SecondRebuildIsTheHubConflict(t *testing.T) {
	r, ri := newIndexTestServer(t, "alpha")

	// Hold the hub's rebuild slot the way a running rebuild would, without
	// depending on one finishing slowly enough to race.
	hub := ri.TaskHub()
	if hub == nil {
		t.Fatal("no task hub")
	}
	blocked := make(chan struct{})
	if _, err := hub.Start("rebuild", func(ctx context.Context, emit func(repos.TaskEvent)) {
		<-blocked
	}); err != nil {
		t.Fatalf("occupy the rebuild slot: %v", err)
	}
	defer close(blocked)

	rec, stop := openIndexStream(t, r)
	defer stop()

	// The index is READY, so the index-state check passes and the request
	// reaches hub.Start, which refuses it.
	resp := postRebuild(t, r, "alpha")
	if resp.Code != http.StatusConflict {
		t.Fatalf("second rebuild: got %d, want 409\nbody: %s", resp.Code, resp.Body.String())
	}
	var problem struct {
		Title string `json:"title"`
	}
	if err := json.Unmarshal(resp.Body.Bytes(), &problem); err != nil {
		t.Fatalf("409 body is not JSON: %v (%s)", err, resp.Body.String())
	}
	if problem.Title != "Job already running" {
		t.Fatalf("409 title = %q, want %q — the index-state check swallowed the hub's conflict",
			problem.Title, "Job already running")
	}

	// AND THE LOSER MARKED NOTHING. This is what makes the mark's placement
	// INSIDE the task fn a tested property rather than a claim in a comment.
	// Marking in the handler instead would flip the state to indexing here and
	// then return 409 with no task left to ever clear it — the index pinned at
	// "indexing" forever, which is the 2026-08 stuck-indexing failure reached
	// by a new route. Every other test in this file passes against that
	// rearrangement; this is the one that does not.
	if state, _, _ := ri.IndexStatus(); state != "ready" {
		t.Fatalf("IndexStatus after a refused rebuild = %q, want ready — the losing request marked, "+
			"and nothing will clear it", state)
	}
	if frames := indexFrames(t, rec.body()); len(frames) != 0 {
		t.Fatalf("refused rebuild emitted %d index frames, want 0: %+v", len(frames), frames)
	}
}

// A FAILING REBUILD MUST ANNOUNCE `error`, not fall silent. A rebuild that
// returned without marking would pin the chip at "indexing" forever, which is
// the stuck-indexing failure reached by a new route — and the rebuild path is
// now one of the routes that can reach it.
//
// Driven through the terminal mark rather than by breaking a store, for the
// same reason TestRepoIndexEvents_FailedHealEmitsError is: inducing a real
// Rebuild failure would test the inducement. What this pins is that the error
// branch of the bracket marks `error` and publishes it — the branch the
// endpoint takes when Rebuild returns non-nil.
func TestRebuild_FailureMarksError(t *testing.T) {
	r, ri := newIndexTestServer(t, "alpha")

	rec, stop := openIndexStream(t, r)
	defer stop()

	ri.MarkIndexRebuildStart()
	ri.MarkIndexRebuildDone(errors.New("rebuild exploded"))

	body := rec.waitFor(t, "an error frame", func(b string) bool {
		for _, e := range indexFrames(t, b) {
			if e.Repo == "alpha" && e.State == "error" {
				return true
			}
		}
		return false
	})
	if state, _, _ := ri.IndexStatus(); state != "error" {
		t.Fatalf("IndexStatus = %q, want error (the event must not outrun the state)", state)
	}

	got := states(indexFrames(t, body))
	if len(got) < 2 || got[0] != "indexing" || got[len(got)-1] != "error" {
		t.Fatalf("state sequence = %v, want indexing … error\nbody:\n%s", got, body)
	}
}

// THE SUCCESS BRACKET, at the unit level: a nil error marks ready. Paired with
// the test above so neither branch of MarkIndexRebuildDone can be deleted
// without a failure — a single-branch test would pass against a bracket that
// marked the same terminal either way.
func TestMarkIndexRebuildDone_NilMarksReady(t *testing.T) {
	_, ri := newIndexTestServer(t, "alpha")

	ri.MarkIndexRebuildStart()
	if state, _, _ := ri.IndexStatus(); state != "indexing" {
		t.Fatalf("after MarkIndexRebuildStart: %q, want indexing", state)
	}
	ri.MarkIndexRebuildDone(nil)
	if state, _, _ := ri.IndexStatus(); state != "ready" {
		t.Fatalf("after MarkIndexRebuildDone(nil): %q, want ready", state)
	}
}
