// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/detect (interfaces: BlockScorer)
//
// Generated by this command:
//
//	mockgen -destination=internal/web/mock_block_scorer_test.go -package=web knomit/internal/detect BlockScorer
//

// Package web is a generated GoMock package.
package web

import (
	detect "knomit/internal/detect"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBlockScorer is a mock of BlockScorer interface.
type MockBlockScorer struct {
	ctrl     *gomock.Controller
	recorder *MockBlockScorerMockRecorder
	isgomock struct{}
}

// MockBlockScorerMockRecorder is the mock recorder for MockBlockScorer.
type MockBlockScorerMockRecorder struct {
	mock *MockBlockScorer
}

// NewMockBlockScorer creates a new mock instance.
func NewMockBlockScorer(ctrl *gomock.Controller) *MockBlockScorer {
	mock := &MockBlockScorer{ctrl: ctrl}
	mock.recorder = &MockBlockScorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockScorer) EXPECT() *MockBlockScorerMockRecorder {
	return m.recorder
}

// ScoreBlocks mocks base method.
func (m *MockBlockScorer) ScoreBlocks(blocks []detect.Block, intentNames []string) []detect.BlockResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScoreBlocks", blocks, intentNames)
	ret0, _ := ret[0].([]detect.BlockResult)
	return ret0
}

// ScoreBlocks indicates an expected call of ScoreBlocks.
func (mr *MockBlockScorerMockRecorder) ScoreBlocks(blocks, intentNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScoreBlocks", reflect.TypeOf((*MockBlockScorer)(nil).ScoreBlocks), blocks, intentNames)
}

// ScoreBlocksWithNovelty mocks base method.
func (m *MockBlockScorer) ScoreBlocksWithNovelty(blocks []detect.Block, intentNames []string, searcher detect.FactSearcher) []detect.BlockResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScoreBlocksWithNovelty", blocks, intentNames, searcher)
	ret0, _ := ret[0].([]detect.BlockResult)
	return ret0
}

// ScoreBlocksWithNovelty indicates an expected call of ScoreBlocksWithNovelty.
func (mr *MockBlockScorerMockRecorder) ScoreBlocksWithNovelty(blocks, intentNames, searcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScoreBlocksWithNovelty", reflect.TypeOf((*MockBlockScorer)(nil).ScoreBlocksWithNovelty), blocks, intentNames, searcher)
}
