// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/repos (interfaces: GitStore,SearchIndex)
//
// Generated by this command:
//
//	mockgen -destination=internal/web/mock_deps_test.go -package=web knomit/internal/repos GitStore,SearchIndex
//

// Package web is a generated GoMock package.
package web

import (
	git "knomit/internal/git"
	store "knomit/internal/store"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitStore is a mock of GitStore interface.
type MockGitStore struct {
	ctrl     *gomock.Controller
	recorder *MockGitStoreMockRecorder
	isgomock struct{}
}

// MockGitStoreMockRecorder is the mock recorder for MockGitStore.
type MockGitStoreMockRecorder struct {
	mock *MockGitStore
}

// NewMockGitStore creates a new mock instance.
func NewMockGitStore(ctrl *gomock.Controller) *MockGitStore {
	mock := &MockGitStore{ctrl: ctrl}
	mock.recorder = &MockGitStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitStore) EXPECT() *MockGitStoreMockRecorder {
	return m.recorder
}

// Activity mocks base method.
func (m *MockGitStore) Activity(branch, path string) (git.ActivityResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activity", branch, path)
	ret0, _ := ret[0].(git.ActivityResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Activity indicates an expected call of Activity.
func (mr *MockGitStoreMockRecorder) Activity(branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activity", reflect.TypeOf((*MockGitStore)(nil).Activity), branch, path)
}

// CommitDetail mocks base method.
func (m *MockGitStore) CommitDetail(commitHash string) (*git.CommitDetailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitDetail", commitHash)
	ret0, _ := ret[0].(*git.CommitDetailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitDetail indicates an expected call of CommitDetail.
func (mr *MockGitStoreMockRecorder) CommitDetail(commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitDetail", reflect.TypeOf((*MockGitStore)(nil).CommitDetail), commitHash)
}

// DeleteFile mocks base method.
func (m *MockGitStore) DeleteFile(branch, path, message, operation string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", branch, path, message, operation)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockGitStoreMockRecorder) DeleteFile(branch, path, message, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockGitStore)(nil).DeleteFile), branch, path, message, operation)
}

// HeadCommit mocks base method.
func (m *MockGitStore) HeadCommit(branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadCommit", branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadCommit indicates an expected call of HeadCommit.
func (mr *MockGitStoreMockRecorder) HeadCommit(branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadCommit", reflect.TypeOf((*MockGitStore)(nil).HeadCommit), branch)
}

// ListAll mocks base method.
func (m *MockGitStore) ListAll(branch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", branch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockGitStoreMockRecorder) ListAll(branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockGitStore)(nil).ListAll), branch)
}

// ListDir mocks base method.
func (m *MockGitStore) ListDir(branch, path string) ([]git.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDir", branch, path)
	ret0, _ := ret[0].([]git.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDir indicates an expected call of ListDir.
func (mr *MockGitStoreMockRecorder) ListDir(branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDir", reflect.TypeOf((*MockGitStore)(nil).ListDir), branch, path)
}

// Log mocks base method.
func (m *MockGitStore) Log(branch, path string) ([]git.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", branch, path)
	ret0, _ := ret[0].([]git.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockGitStoreMockRecorder) Log(branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockGitStore)(nil).Log), branch, path)
}

// LogPaginated mocks base method.
func (m *MockGitStore) LogPaginated(branch, path string, limit int, after, from, before string) ([]git.LogEntryWithTags, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogPaginated", branch, path, limit, after, from, before)
	ret0, _ := ret[0].([]git.LogEntryWithTags)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LogPaginated indicates an expected call of LogPaginated.
func (mr *MockGitStoreMockRecorder) LogPaginated(branch, path, limit, after, from, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPaginated", reflect.TypeOf((*MockGitStore)(nil).LogPaginated), branch, path, limit, after, from, before)
}

// ReadFile mocks base method.
func (m *MockGitStore) ReadFile(branch, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", branch, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockGitStoreMockRecorder) ReadFile(branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockGitStore)(nil).ReadFile), branch, path)
}

// ReadFileAtCommit mocks base method.
func (m *MockGitStore) ReadFileAtCommit(branch, path, commitHash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileAtCommit", branch, path, commitHash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileAtCommit indicates an expected call of ReadFileAtCommit.
func (mr *MockGitStoreMockRecorder) ReadFileAtCommit(branch, path, commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileAtCommit", reflect.TypeOf((*MockGitStore)(nil).ReadFileAtCommit), branch, path, commitHash)
}

// ReadFileLastCommit mocks base method.
func (m *MockGitStore) ReadFileLastCommit(branch, path, beforeCommitHash string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileLastCommit", branch, path, beforeCommitHash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadFileLastCommit indicates an expected call of ReadFileLastCommit.
func (mr *MockGitStoreMockRecorder) ReadFileLastCommit(branch, path, beforeCommitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileLastCommit", reflect.TypeOf((*MockGitStore)(nil).ReadFileLastCommit), branch, path, beforeCommitHash)
}

// WriteFile mocks base method.
func (m *MockGitStore) WriteFile(branch, path, content, message, operation string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", branch, path, content, message, operation)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockGitStoreMockRecorder) WriteFile(branch, path, content, message, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockGitStore)(nil).WriteFile), branch, path, content, message, operation)
}

// MockSearchIndex is a mock of SearchIndex interface.
type MockSearchIndex struct {
	ctrl     *gomock.Controller
	recorder *MockSearchIndexMockRecorder
	isgomock struct{}
}

// MockSearchIndexMockRecorder is the mock recorder for MockSearchIndex.
type MockSearchIndexMockRecorder struct {
	mock *MockSearchIndex
}

// NewMockSearchIndex creates a new mock instance.
func NewMockSearchIndex(ctrl *gomock.Controller) *MockSearchIndex {
	mock := &MockSearchIndex{ctrl: ctrl}
	mock.recorder = &MockSearchIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchIndex) EXPECT() *MockSearchIndexMockRecorder {
	return m.recorder
}

// Completions mocks base method.
func (m *MockSearchIndex) Completions(branch, category, prefix string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Completions", branch, category, prefix, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Completions indicates an expected call of Completions.
func (mr *MockSearchIndexMockRecorder) Completions(branch, category, prefix, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Completions", reflect.TypeOf((*MockSearchIndex)(nil).Completions), branch, category, prefix, limit)
}

// ExplainFact mocks base method.
func (m *MockSearchIndex) ExplainFact(branch, path string) (store.ExplainResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExplainFact", branch, path)
	ret0, _ := ret[0].(store.ExplainResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExplainFact indicates an expected call of ExplainFact.
func (mr *MockSearchIndexMockRecorder) ExplainFact(branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExplainFact", reflect.TypeOf((*MockSearchIndex)(nil).ExplainFact), branch, path)
}

// GetByPath mocks base method.
func (m *MockSearchIndex) GetByPath(branch, path string) (*store.FactWithBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", branch, path)
	ret0, _ := ret[0].(*store.FactWithBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockSearchIndexMockRecorder) GetByPath(branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockSearchIndex)(nil).GetByPath), branch, path)
}

// GetLastCommit mocks base method.
func (m *MockSearchIndex) GetLastCommit(branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommit", branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommit indicates an expected call of GetLastCommit.
func (mr *MockSearchIndexMockRecorder) GetLastCommit(branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommit", reflect.TypeOf((*MockSearchIndex)(nil).GetLastCommit), branch)
}

// Search mocks base method.
func (m *MockSearchIndex) Search(branch string, q store.SearchQuery) ([]store.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", branch, q)
	ret0, _ := ret[0].([]store.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchIndexMockRecorder) Search(branch, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchIndex)(nil).Search), branch, q)
}

// Stats mocks base method.
func (m *MockSearchIndex) Stats(branch, pathPrefix string) (store.StatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", branch, pathPrefix)
	ret0, _ := ret[0].(store.StatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockSearchIndexMockRecorder) Stats(branch, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockSearchIndex)(nil).Stats), branch, pathPrefix)
}
