// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/web (interfaces: GitStore,SearchIndex)
//
// Generated by this command:
//
//	mockgen -destination=internal/web/mock_deps_test.go -package=web knomit/internal/web GitStore,SearchIndex
//

// Package web is a generated GoMock package.
package web

import (
	git "knomit/internal/git"
	store "knomit/internal/store"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitStore is a mock of GitStore interface.
type MockGitStore struct {
	ctrl     *gomock.Controller
	recorder *MockGitStoreMockRecorder
	isgomock struct{}
}

// MockGitStoreMockRecorder is the mock recorder for MockGitStore.
type MockGitStoreMockRecorder struct {
	mock *MockGitStore
}

// NewMockGitStore creates a new mock instance.
func NewMockGitStore(ctrl *gomock.Controller) *MockGitStore {
	mock := &MockGitStore{ctrl: ctrl}
	mock.recorder = &MockGitStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitStore) EXPECT() *MockGitStoreMockRecorder {
	return m.recorder
}

// Branch mocks base method.
func (m *MockGitStore) Branch() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Branch")
	ret0, _ := ret[0].(string)
	return ret0
}

// Branch indicates an expected call of Branch.
func (mr *MockGitStoreMockRecorder) Branch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Branch", reflect.TypeOf((*MockGitStore)(nil).Branch))
}

// HeadCommit mocks base method.
func (m *MockGitStore) HeadCommit() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadCommit")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadCommit indicates an expected call of HeadCommit.
func (mr *MockGitStoreMockRecorder) HeadCommit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadCommit", reflect.TypeOf((*MockGitStore)(nil).HeadCommit))
}

// ListAll mocks base method.
func (m *MockGitStore) ListAll() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockGitStoreMockRecorder) ListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockGitStore)(nil).ListAll))
}

// ListDir mocks base method.
func (m *MockGitStore) ListDir(path string) ([]git.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDir", path)
	ret0, _ := ret[0].([]git.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDir indicates an expected call of ListDir.
func (mr *MockGitStoreMockRecorder) ListDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDir", reflect.TypeOf((*MockGitStore)(nil).ListDir), path)
}

// Log mocks base method.
func (m *MockGitStore) Log(path string) ([]git.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", path)
	ret0, _ := ret[0].([]git.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockGitStoreMockRecorder) Log(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockGitStore)(nil).Log), path)
}

// ReadFile mocks base method.
func (m *MockGitStore) ReadFile(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockGitStoreMockRecorder) ReadFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockGitStore)(nil).ReadFile), path)
}

// Sync mocks base method.
func (m *MockGitStore) Sync(remoteAuth any) (git.SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", remoteAuth)
	ret0, _ := ret[0].(git.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockGitStoreMockRecorder) Sync(remoteAuth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockGitStore)(nil).Sync), remoteAuth)
}

// MockSearchIndex is a mock of SearchIndex interface.
type MockSearchIndex struct {
	ctrl     *gomock.Controller
	recorder *MockSearchIndexMockRecorder
	isgomock struct{}
}

// MockSearchIndexMockRecorder is the mock recorder for MockSearchIndex.
type MockSearchIndexMockRecorder struct {
	mock *MockSearchIndex
}

// NewMockSearchIndex creates a new mock instance.
func NewMockSearchIndex(ctrl *gomock.Controller) *MockSearchIndex {
	mock := &MockSearchIndex{ctrl: ctrl}
	mock.recorder = &MockSearchIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchIndex) EXPECT() *MockSearchIndexMockRecorder {
	return m.recorder
}

// GetLastCommit mocks base method.
func (m *MockSearchIndex) GetLastCommit(branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommit", branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommit indicates an expected call of GetLastCommit.
func (mr *MockSearchIndexMockRecorder) GetLastCommit(branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommit", reflect.TypeOf((*MockSearchIndex)(nil).GetLastCommit), branch)
}

// Search mocks base method.
func (m *MockSearchIndex) Search(q store.SearchQuery) ([]store.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", q)
	ret0, _ := ret[0].([]store.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchIndexMockRecorder) Search(q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchIndex)(nil).Search), q)
}
