// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/store (interfaces: IndexManager)
//
// Generated by this command:
//
//	mockgen -destination=internal/repos/mock_index_manager_test.go -package=repos knomit/internal/store IndexManager
//

// Package repos is a generated GoMock package.
package repos

import (
	context "context"
	store "knomit/internal/store"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIndexManager is a mock of IndexManager interface.
type MockIndexManager struct {
	ctrl     *gomock.Controller
	recorder *MockIndexManagerMockRecorder
	isgomock struct{}
}

// MockIndexManagerMockRecorder is the mock recorder for MockIndexManager.
type MockIndexManagerMockRecorder struct {
	mock *MockIndexManager
}

// NewMockIndexManager creates a new mock instance.
func NewMockIndexManager(ctrl *gomock.Controller) *MockIndexManager {
	mock := &MockIndexManager{ctrl: ctrl}
	mock.recorder = &MockIndexManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexManager) EXPECT() *MockIndexManagerMockRecorder {
	return m.recorder
}

// NeedsRebuild mocks base method.
func (m *MockIndexManager) NeedsRebuild(ctx context.Context, branch string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NeedsRebuild", ctx, branch)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NeedsRebuild indicates an expected call of NeedsRebuild.
func (mr *MockIndexManagerMockRecorder) NeedsRebuild(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NeedsRebuild", reflect.TypeOf((*MockIndexManager)(nil).NeedsRebuild), ctx, branch)
}

// Rebuild mocks base method.
func (m *MockIndexManager) Rebuild(ctx context.Context, branch string, progress store.RebuildProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rebuild", ctx, branch, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rebuild indicates an expected call of Rebuild.
func (mr *MockIndexManagerMockRecorder) Rebuild(ctx, branch, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rebuild", reflect.TypeOf((*MockIndexManager)(nil).Rebuild), ctx, branch, progress)
}

// Sync mocks base method.
func (m *MockIndexManager) Sync(ctx context.Context, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockIndexManagerMockRecorder) Sync(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockIndexManager)(nil).Sync), ctx, branch)
}

// SyncLocked mocks base method.
func (m *MockIndexManager) SyncLocked(ctx context.Context, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncLocked", ctx, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncLocked indicates an expected call of SyncLocked.
func (mr *MockIndexManagerMockRecorder) SyncLocked(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncLocked", reflect.TypeOf((*MockIndexManager)(nil).SyncLocked), ctx, branch)
}

// SyncWatermark mocks base method.
func (m *MockIndexManager) SyncWatermark(ctx context.Context, branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncWatermark", ctx, branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncWatermark indicates an expected call of SyncWatermark.
func (mr *MockIndexManagerMockRecorder) SyncWatermark(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncWatermark", reflect.TypeOf((*MockIndexManager)(nil).SyncWatermark), ctx, branch)
}
