// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/mcp (interfaces: GitStore,SearchIndex,ExploreIndex)
//
// Generated by this command:
//
//	mockgen -destination=internal/mcp/mock_store_test.go -package=mcp knomit/internal/mcp GitStore,SearchIndex,ExploreIndex
//

// Package mcp is a generated GoMock package.
package mcp

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitStore is a mock of GitStore interface.
type MockGitStore struct {
	ctrl     *gomock.Controller
	recorder *MockGitStoreMockRecorder
	isgomock struct{}
}

// MockGitStoreMockRecorder is the mock recorder for MockGitStore.
type MockGitStoreMockRecorder struct {
	mock *MockGitStore
}

// NewMockGitStore creates a new mock instance.
func NewMockGitStore(ctrl *gomock.Controller) *MockGitStore {
	mock := &MockGitStore{ctrl: ctrl}
	mock.recorder = &MockGitStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitStore) EXPECT() *MockGitStoreMockRecorder {
	return m.recorder
}

// BatchWrite mocks base method.
func (m *MockGitStore) BatchWrite(files map[string]string, message string) (string, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchWrite", files, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BatchWrite indicates an expected call of BatchWrite.
func (mr *MockGitStoreMockRecorder) BatchWrite(files, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchWrite", reflect.TypeOf((*MockGitStore)(nil).BatchWrite), files, message)
}

// Branch mocks base method.
func (m *MockGitStore) Branch() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Branch")
	ret0, _ := ret[0].(string)
	return ret0
}

// Branch indicates an expected call of Branch.
func (mr *MockGitStoreMockRecorder) Branch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Branch", reflect.TypeOf((*MockGitStore)(nil).Branch))
}

// DeleteFile mocks base method.
func (m *MockGitStore) DeleteFile(path, message string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", path, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockGitStoreMockRecorder) DeleteFile(path, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockGitStore)(nil).DeleteFile), path, message)
}

// DiffFiles mocks base method.
func (m *MockGitStore) DiffFiles(fromCommit string) ([]string, []string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiffFiles", fromCommit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].([]string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// DiffFiles indicates an expected call of DiffFiles.
func (mr *MockGitStoreMockRecorder) DiffFiles(fromCommit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffFiles", reflect.TypeOf((*MockGitStore)(nil).DiffFiles), fromCommit)
}

// FileExists mocks base method.
func (m *MockGitStore) FileExists(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockGitStoreMockRecorder) FileExists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockGitStore)(nil).FileExists), path)
}

// Grep mocks base method.
func (m *MockGitStore) Grep(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Grep", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Grep indicates an expected call of Grep.
func (mr *MockGitStoreMockRecorder) Grep(pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grep", reflect.TypeOf((*MockGitStore)(nil).Grep), pattern)
}

// HeadCommit mocks base method.
func (m *MockGitStore) HeadCommit() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadCommit")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadCommit indicates an expected call of HeadCommit.
func (mr *MockGitStoreMockRecorder) HeadCommit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadCommit", reflect.TypeOf((*MockGitStore)(nil).HeadCommit))
}

// ListAll mocks base method.
func (m *MockGitStore) ListAll() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockGitStoreMockRecorder) ListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockGitStore)(nil).ListAll))
}

// ListDir mocks base method.
func (m *MockGitStore) ListDir(path string) ([]DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDir", path)
	ret0, _ := ret[0].([]DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDir indicates an expected call of ListDir.
func (mr *MockGitStoreMockRecorder) ListDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDir", reflect.TypeOf((*MockGitStore)(nil).ListDir), path)
}

// Log mocks base method.
func (m *MockGitStore) Log(path string) ([]LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", path)
	ret0, _ := ret[0].([]LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockGitStoreMockRecorder) Log(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockGitStore)(nil).Log), path)
}

// ReadFile mocks base method.
func (m *MockGitStore) ReadFile(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockGitStoreMockRecorder) ReadFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockGitStore)(nil).ReadFile), path)
}

// ReadFileWithHash mocks base method.
func (m *MockGitStore) ReadFileWithHash(path string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileWithHash", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadFileWithHash indicates an expected call of ReadFileWithHash.
func (mr *MockGitStoreMockRecorder) ReadFileWithHash(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileWithHash", reflect.TypeOf((*MockGitStore)(nil).ReadFileWithHash), path)
}

// Tag mocks base method.
func (m *MockGitStore) Tag(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Tag indicates an expected call of Tag.
func (mr *MockGitStoreMockRecorder) Tag(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockGitStore)(nil).Tag), name)
}

// TagsContaining mocks base method.
func (m *MockGitStore) TagsContaining(hash string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagsContaining", hash)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagsContaining indicates an expected call of TagsContaining.
func (mr *MockGitStoreMockRecorder) TagsContaining(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagsContaining", reflect.TypeOf((*MockGitStore)(nil).TagsContaining), hash)
}

// WalkChangedFiles mocks base method.
func (m *MockGitStore) WalkChangedFiles(fromCommit, prefix string, seen map[string]bool, limit int) ([]FileRecency, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalkChangedFiles", fromCommit, prefix, seen, limit)
	ret0, _ := ret[0].([]FileRecency)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WalkChangedFiles indicates an expected call of WalkChangedFiles.
func (mr *MockGitStoreMockRecorder) WalkChangedFiles(fromCommit, prefix, seen, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalkChangedFiles", reflect.TypeOf((*MockGitStore)(nil).WalkChangedFiles), fromCommit, prefix, seen, limit)
}

// WriteFile mocks base method.
func (m *MockGitStore) WriteFile(path, content, message string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", path, content, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockGitStoreMockRecorder) WriteFile(path, content, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockGitStore)(nil).WriteFile), path, content, message)
}

// MockSearchIndex is a mock of SearchIndex interface.
type MockSearchIndex struct {
	ctrl     *gomock.Controller
	recorder *MockSearchIndexMockRecorder
	isgomock struct{}
}

// MockSearchIndexMockRecorder is the mock recorder for MockSearchIndex.
type MockSearchIndexMockRecorder struct {
	mock *MockSearchIndex
}

// NewMockSearchIndex creates a new mock instance.
func NewMockSearchIndex(ctrl *gomock.Controller) *MockSearchIndex {
	mock := &MockSearchIndex{ctrl: ctrl}
	mock.recorder = &MockSearchIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchIndex) EXPECT() *MockSearchIndexMockRecorder {
	return m.recorder
}

// GetByPath mocks base method.
func (m *MockSearchIndex) GetByPath(path string) (*FactWithBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", path)
	ret0, _ := ret[0].(*FactWithBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockSearchIndexMockRecorder) GetByPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockSearchIndex)(nil).GetByPath), path)
}

// Search mocks base method.
func (m *MockSearchIndex) Search(q SearchQuery) ([]SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", q)
	ret0, _ := ret[0].([]SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchIndexMockRecorder) Search(q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchIndex)(nil).Search), q)
}

// MockExploreIndex is a mock of ExploreIndex interface.
type MockExploreIndex struct {
	ctrl     *gomock.Controller
	recorder *MockExploreIndexMockRecorder
	isgomock struct{}
}

// MockExploreIndexMockRecorder is the mock recorder for MockExploreIndex.
type MockExploreIndexMockRecorder struct {
	mock *MockExploreIndex
}

// NewMockExploreIndex creates a new mock instance.
func NewMockExploreIndex(ctrl *gomock.Controller) *MockExploreIndex {
	mock := &MockExploreIndex{ctrl: ctrl}
	mock.recorder = &MockExploreIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExploreIndex) EXPECT() *MockExploreIndexMockRecorder {
	return m.recorder
}

// AddExploreSeenPaths mocks base method.
func (m *MockExploreIndex) AddExploreSeenPaths(sessionID string, paths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExploreSeenPaths", sessionID, paths)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExploreSeenPaths indicates an expected call of AddExploreSeenPaths.
func (mr *MockExploreIndexMockRecorder) AddExploreSeenPaths(sessionID, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExploreSeenPaths", reflect.TypeOf((*MockExploreIndex)(nil).AddExploreSeenPaths), sessionID, paths)
}

// CreateExploreSession mocks base method.
func (m *MockExploreIndex) CreateExploreSession(branch, pathPrefix string) (*ExploreSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExploreSession", branch, pathPrefix)
	ret0, _ := ret[0].(*ExploreSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExploreSession indicates an expected call of CreateExploreSession.
func (mr *MockExploreIndexMockRecorder) CreateExploreSession(branch, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExploreSession", reflect.TypeOf((*MockExploreIndex)(nil).CreateExploreSession), branch, pathPrefix)
}

// GCExploreSessions mocks base method.
func (m *MockExploreIndex) GCExploreSessions(branch string, keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GCExploreSessions", branch, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// GCExploreSessions indicates an expected call of GCExploreSessions.
func (mr *MockExploreIndexMockRecorder) GCExploreSessions(branch, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GCExploreSessions", reflect.TypeOf((*MockExploreIndex)(nil).GCExploreSessions), branch, keep)
}

// GetExploreSeenPaths mocks base method.
func (m *MockExploreIndex) GetExploreSeenPaths(sessionID string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExploreSeenPaths", sessionID)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExploreSeenPaths indicates an expected call of GetExploreSeenPaths.
func (mr *MockExploreIndexMockRecorder) GetExploreSeenPaths(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExploreSeenPaths", reflect.TypeOf((*MockExploreIndex)(nil).GetExploreSeenPaths), sessionID)
}

// GetExploreSession mocks base method.
func (m *MockExploreIndex) GetExploreSession(id string) (*ExploreSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExploreSession", id)
	ret0, _ := ret[0].(*ExploreSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExploreSession indicates an expected call of GetExploreSession.
func (mr *MockExploreIndexMockRecorder) GetExploreSession(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExploreSession", reflect.TypeOf((*MockExploreIndex)(nil).GetExploreSession), id)
}

// UpdateExploreSession mocks base method.
func (m *MockExploreIndex) UpdateExploreSession(id, lastCommit, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExploreSession", id, lastCommit, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExploreSession indicates an expected call of UpdateExploreSession.
func (mr *MockExploreIndexMockRecorder) UpdateExploreSession(id, lastCommit, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExploreSession", reflect.TypeOf((*MockExploreIndex)(nil).UpdateExploreSession), id, lastCommit, status)
}
