// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/store (interfaces: PipelineIndex)
//
// Generated by this command:
//
//	mockgen -destination=internal/mcp/mock_pipeline_index_test.go -package=mcp knomit/internal/store PipelineIndex
//

// Package mcp is a generated GoMock package.
package mcp

import (
	context "context"
	store "knomit/internal/store"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPipelineIndex is a mock of PipelineIndex interface.
type MockPipelineIndex struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineIndexMockRecorder
	isgomock struct{}
}

// MockPipelineIndexMockRecorder is the mock recorder for MockPipelineIndex.
type MockPipelineIndexMockRecorder struct {
	mock *MockPipelineIndex
}

// NewMockPipelineIndex creates a new mock instance.
func NewMockPipelineIndex(ctrl *gomock.Controller) *MockPipelineIndex {
	mock := &MockPipelineIndex{ctrl: ctrl}
	mock.recorder = &MockPipelineIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineIndex) EXPECT() *MockPipelineIndexMockRecorder {
	return m.recorder
}

// AdvancePipelineSessionPhase mocks base method.
func (m *MockPipelineIndex) AdvancePipelineSessionPhase(ctx context.Context, id, from, to string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvancePipelineSessionPhase", ctx, id, from, to)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdvancePipelineSessionPhase indicates an expected call of AdvancePipelineSessionPhase.
func (mr *MockPipelineIndexMockRecorder) AdvancePipelineSessionPhase(ctx, id, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvancePipelineSessionPhase", reflect.TypeOf((*MockPipelineIndex)(nil).AdvancePipelineSessionPhase), ctx, id, from, to)
}

// CompletePipelineSession mocks base method.
func (m *MockPipelineIndex) CompletePipelineSession(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompletePipelineSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompletePipelineSession indicates an expected call of CompletePipelineSession.
func (mr *MockPipelineIndexMockRecorder) CompletePipelineSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompletePipelineSession", reflect.TypeOf((*MockPipelineIndex)(nil).CompletePipelineSession), ctx, id)
}

// CreatePipelineSession mocks base method.
func (m *MockPipelineIndex) CreatePipelineSession(ctx context.Context, tool, branch string) (*store.PipelineSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipelineSession", ctx, tool, branch)
	ret0, _ := ret[0].(*store.PipelineSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipelineSession indicates an expected call of CreatePipelineSession.
func (mr *MockPipelineIndexMockRecorder) CreatePipelineSession(ctx, tool, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipelineSession", reflect.TypeOf((*MockPipelineIndex)(nil).CreatePipelineSession), ctx, tool, branch)
}

// GetPipelineSession mocks base method.
func (m *MockPipelineIndex) GetPipelineSession(ctx context.Context, id string) (*store.PipelineSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineSession", ctx, id)
	ret0, _ := ret[0].(*store.PipelineSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineSession indicates an expected call of GetPipelineSession.
func (mr *MockPipelineIndexMockRecorder) GetPipelineSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineSession", reflect.TypeOf((*MockPipelineIndex)(nil).GetPipelineSession), ctx, id)
}

// GetPipelineWatermark mocks base method.
func (m *MockPipelineIndex) GetPipelineWatermark(ctx context.Context, tool, branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineWatermark", ctx, tool, branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineWatermark indicates an expected call of GetPipelineWatermark.
func (mr *MockPipelineIndexMockRecorder) GetPipelineWatermark(ctx, tool, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineWatermark", reflect.TypeOf((*MockPipelineIndex)(nil).GetPipelineWatermark), ctx, tool, branch)
}

// InsertPipelineWorkItem mocks base method.
func (m *MockPipelineIndex) InsertPipelineWorkItem(ctx context.Context, item store.PipelineWorkItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPipelineWorkItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPipelineWorkItem indicates an expected call of InsertPipelineWorkItem.
func (mr *MockPipelineIndexMockRecorder) InsertPipelineWorkItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPipelineWorkItem", reflect.TypeOf((*MockPipelineIndex)(nil).InsertPipelineWorkItem), ctx, item)
}

// MarkPipelineSessionScoped mocks base method.
func (m *MockPipelineIndex) MarkPipelineSessionScoped(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPipelineSessionScoped", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPipelineSessionScoped indicates an expected call of MarkPipelineSessionScoped.
func (mr *MockPipelineIndexMockRecorder) MarkPipelineSessionScoped(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPipelineSessionScoped", reflect.TypeOf((*MockPipelineIndex)(nil).MarkPipelineSessionScoped), ctx, id)
}

// NextPipelineWorkItem mocks base method.
func (m *MockPipelineIndex) NextPipelineWorkItem(ctx context.Context, sessionID string) (*store.PipelineWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPipelineWorkItem", ctx, sessionID)
	ret0, _ := ret[0].(*store.PipelineWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPipelineWorkItem indicates an expected call of NextPipelineWorkItem.
func (mr *MockPipelineIndexMockRecorder) NextPipelineWorkItem(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPipelineWorkItem", reflect.TypeOf((*MockPipelineIndex)(nil).NextPipelineWorkItem), ctx, sessionID)
}

// PipelineWorkItemStats mocks base method.
func (m *MockPipelineIndex) PipelineWorkItemStats(ctx context.Context, sessionID string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PipelineWorkItemStats", ctx, sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PipelineWorkItemStats indicates an expected call of PipelineWorkItemStats.
func (mr *MockPipelineIndexMockRecorder) PipelineWorkItemStats(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PipelineWorkItemStats", reflect.TypeOf((*MockPipelineIndex)(nil).PipelineWorkItemStats), ctx, sessionID)
}

// SetPipelineWatermark mocks base method.
func (m *MockPipelineIndex) SetPipelineWatermark(ctx context.Context, tool, branch, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPipelineWatermark", ctx, tool, branch, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPipelineWatermark indicates an expected call of SetPipelineWatermark.
func (mr *MockPipelineIndexMockRecorder) SetPipelineWatermark(ctx, tool, branch, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPipelineWatermark", reflect.TypeOf((*MockPipelineIndex)(nil).SetPipelineWatermark), ctx, tool, branch, hash)
}

// SetPipelineWorkItemResponse mocks base method.
func (m *MockPipelineIndex) SetPipelineWorkItemResponse(ctx context.Context, id int64, response string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPipelineWorkItemResponse", ctx, id, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPipelineWorkItemResponse indicates an expected call of SetPipelineWorkItemResponse.
func (mr *MockPipelineIndexMockRecorder) SetPipelineWorkItemResponse(ctx, id, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPipelineWorkItemResponse", reflect.TypeOf((*MockPipelineIndex)(nil).SetPipelineWorkItemResponse), ctx, id, response)
}
