// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/mcp (interfaces: GitStore,SearchIndex,ToolSessionIndex)
//
// Generated by this command:
//
//	mockgen -destination=internal/mcp/mock_store_test.go -package=mcp knomit/internal/mcp GitStore,SearchIndex,ToolSessionIndex
//

// Package mcp is a generated GoMock package.
package mcp

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitStore is a mock of GitStore interface.
type MockGitStore struct {
	ctrl     *gomock.Controller
	recorder *MockGitStoreMockRecorder
	isgomock struct{}
}

// MockGitStoreMockRecorder is the mock recorder for MockGitStore.
type MockGitStoreMockRecorder struct {
	mock *MockGitStore
}

// NewMockGitStore creates a new mock instance.
func NewMockGitStore(ctrl *gomock.Controller) *MockGitStore {
	mock := &MockGitStore{ctrl: ctrl}
	mock.recorder = &MockGitStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitStore) EXPECT() *MockGitStoreMockRecorder {
	return m.recorder
}

// BatchWrite mocks base method.
func (m *MockGitStore) BatchWrite(files map[string]string, message, operation string) (string, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchWrite", files, message, operation)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BatchWrite indicates an expected call of BatchWrite.
func (mr *MockGitStoreMockRecorder) BatchWrite(files, message, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchWrite", reflect.TypeOf((*MockGitStore)(nil).BatchWrite), files, message, operation)
}

// Branch mocks base method.
func (m *MockGitStore) Branch() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Branch")
	ret0, _ := ret[0].(string)
	return ret0
}

// Branch indicates an expected call of Branch.
func (mr *MockGitStoreMockRecorder) Branch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Branch", reflect.TypeOf((*MockGitStore)(nil).Branch))
}

// DeleteFile mocks base method.
func (m *MockGitStore) DeleteFile(path, message, operation string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", path, message, operation)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockGitStoreMockRecorder) DeleteFile(path, message, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockGitStore)(nil).DeleteFile), path, message, operation)
}

// DiffFiles mocks base method.
func (m *MockGitStore) DiffFiles(fromCommit string) ([]string, []string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiffFiles", fromCommit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].([]string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// DiffFiles indicates an expected call of DiffFiles.
func (mr *MockGitStoreMockRecorder) DiffFiles(fromCommit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffFiles", reflect.TypeOf((*MockGitStore)(nil).DiffFiles), fromCommit)
}

// FileExists mocks base method.
func (m *MockGitStore) FileExists(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockGitStoreMockRecorder) FileExists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockGitStore)(nil).FileExists), path)
}

// Grep mocks base method.
func (m *MockGitStore) Grep(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Grep", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Grep indicates an expected call of Grep.
func (mr *MockGitStoreMockRecorder) Grep(pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grep", reflect.TypeOf((*MockGitStore)(nil).Grep), pattern)
}

// HeadCommit mocks base method.
func (m *MockGitStore) HeadCommit() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadCommit")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadCommit indicates an expected call of HeadCommit.
func (mr *MockGitStoreMockRecorder) HeadCommit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadCommit", reflect.TypeOf((*MockGitStore)(nil).HeadCommit))
}

// LastCommitForPath mocks base method.
func (m *MockGitStore) LastCommitForPath(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastCommitForPath", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastCommitForPath indicates an expected call of LastCommitForPath.
func (mr *MockGitStoreMockRecorder) LastCommitForPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastCommitForPath", reflect.TypeOf((*MockGitStore)(nil).LastCommitForPath), path)
}

// ListAll mocks base method.
func (m *MockGitStore) ListAll() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockGitStoreMockRecorder) ListAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockGitStore)(nil).ListAll))
}

// ListDir mocks base method.
func (m *MockGitStore) ListDir(path string) ([]DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDir", path)
	ret0, _ := ret[0].([]DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDir indicates an expected call of ListDir.
func (mr *MockGitStoreMockRecorder) ListDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDir", reflect.TypeOf((*MockGitStore)(nil).ListDir), path)
}

// Log mocks base method.
func (m *MockGitStore) Log(path string) ([]LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", path)
	ret0, _ := ret[0].([]LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockGitStoreMockRecorder) Log(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockGitStore)(nil).Log), path)
}

// ReadFile mocks base method.
func (m *MockGitStore) ReadFile(path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockGitStoreMockRecorder) ReadFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockGitStore)(nil).ReadFile), path)
}

// ReadFileAtCommit mocks base method.
func (m *MockGitStore) ReadFileAtCommit(path, commitHash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileAtCommit", path, commitHash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileAtCommit indicates an expected call of ReadFileAtCommit.
func (mr *MockGitStoreMockRecorder) ReadFileAtCommit(path, commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileAtCommit", reflect.TypeOf((*MockGitStore)(nil).ReadFileAtCommit), path, commitHash)
}

// ReadFileLastCommit mocks base method.
func (m *MockGitStore) ReadFileLastCommit(path, beforeCommitHash string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileLastCommit", path, beforeCommitHash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadFileLastCommit indicates an expected call of ReadFileLastCommit.
func (mr *MockGitStoreMockRecorder) ReadFileLastCommit(path, beforeCommitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileLastCommit", reflect.TypeOf((*MockGitStore)(nil).ReadFileLastCommit), path, beforeCommitHash)
}

// ReadFileWithHash mocks base method.
func (m *MockGitStore) ReadFileWithHash(path string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileWithHash", path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadFileWithHash indicates an expected call of ReadFileWithHash.
func (mr *MockGitStoreMockRecorder) ReadFileWithHash(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileWithHash", reflect.TypeOf((*MockGitStore)(nil).ReadFileWithHash), path)
}

// WalkChangedFiles mocks base method.
func (m *MockGitStore) WalkChangedFiles(fromCommit, prefix string, seen map[string]bool, limit int) ([]FileRecency, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalkChangedFiles", fromCommit, prefix, seen, limit)
	ret0, _ := ret[0].([]FileRecency)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WalkChangedFiles indicates an expected call of WalkChangedFiles.
func (mr *MockGitStoreMockRecorder) WalkChangedFiles(fromCommit, prefix, seen, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalkChangedFiles", reflect.TypeOf((*MockGitStore)(nil).WalkChangedFiles), fromCommit, prefix, seen, limit)
}

// WriteFile mocks base method.
func (m *MockGitStore) WriteFile(path, content, message, operation string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", path, content, message, operation)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockGitStoreMockRecorder) WriteFile(path, content, message, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockGitStore)(nil).WriteFile), path, content, message, operation)
}

// MockSearchIndex is a mock of SearchIndex interface.
type MockSearchIndex struct {
	ctrl     *gomock.Controller
	recorder *MockSearchIndexMockRecorder
	isgomock struct{}
}

// MockSearchIndexMockRecorder is the mock recorder for MockSearchIndex.
type MockSearchIndexMockRecorder struct {
	mock *MockSearchIndex
}

// NewMockSearchIndex creates a new mock instance.
func NewMockSearchIndex(ctrl *gomock.Controller) *MockSearchIndex {
	mock := &MockSearchIndex{ctrl: ctrl}
	mock.recorder = &MockSearchIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchIndex) EXPECT() *MockSearchIndexMockRecorder {
	return m.recorder
}

// GetByPath mocks base method.
func (m *MockSearchIndex) GetByPath(path string) (*FactWithBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", path)
	ret0, _ := ret[0].(*FactWithBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockSearchIndexMockRecorder) GetByPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockSearchIndex)(nil).GetByPath), path)
}

// Search mocks base method.
func (m *MockSearchIndex) Search(q SearchQuery) ([]SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", q)
	ret0, _ := ret[0].([]SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchIndexMockRecorder) Search(q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchIndex)(nil).Search), q)
}

// MockToolSessionIndex is a mock of ToolSessionIndex interface.
type MockToolSessionIndex struct {
	ctrl     *gomock.Controller
	recorder *MockToolSessionIndexMockRecorder
	isgomock struct{}
}

// MockToolSessionIndexMockRecorder is the mock recorder for MockToolSessionIndex.
type MockToolSessionIndexMockRecorder struct {
	mock *MockToolSessionIndex
}

// NewMockToolSessionIndex creates a new mock instance.
func NewMockToolSessionIndex(ctrl *gomock.Controller) *MockToolSessionIndex {
	mock := &MockToolSessionIndex{ctrl: ctrl}
	mock.recorder = &MockToolSessionIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolSessionIndex) EXPECT() *MockToolSessionIndexMockRecorder {
	return m.recorder
}

// AddSeenPaths mocks base method.
func (m *MockToolSessionIndex) AddSeenPaths(sessionID string, paths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSeenPaths", sessionID, paths)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSeenPaths indicates an expected call of AddSeenPaths.
func (mr *MockToolSessionIndexMockRecorder) AddSeenPaths(sessionID, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSeenPaths", reflect.TypeOf((*MockToolSessionIndex)(nil).AddSeenPaths), sessionID, paths)
}

// CreateToolSession mocks base method.
func (m *MockToolSessionIndex) CreateToolSession(tool, branch, pathPrefix string) (*ToolSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToolSession", tool, branch, pathPrefix)
	ret0, _ := ret[0].(*ToolSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToolSession indicates an expected call of CreateToolSession.
func (mr *MockToolSessionIndexMockRecorder) CreateToolSession(tool, branch, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToolSession", reflect.TypeOf((*MockToolSessionIndex)(nil).CreateToolSession), tool, branch, pathPrefix)
}

// DequeuePaths mocks base method.
func (m *MockToolSessionIndex) DequeuePaths(sessionID string, limit int) ([]QueueItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DequeuePaths", sessionID, limit)
	ret0, _ := ret[0].([]QueueItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DequeuePaths indicates an expected call of DequeuePaths.
func (mr *MockToolSessionIndexMockRecorder) DequeuePaths(sessionID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DequeuePaths", reflect.TypeOf((*MockToolSessionIndex)(nil).DequeuePaths), sessionID, limit)
}

// EnqueuePaths mocks base method.
func (m *MockToolSessionIndex) EnqueuePaths(sessionID string, items []QueueItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueuePaths", sessionID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueuePaths indicates an expected call of EnqueuePaths.
func (mr *MockToolSessionIndexMockRecorder) EnqueuePaths(sessionID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueuePaths", reflect.TypeOf((*MockToolSessionIndex)(nil).EnqueuePaths), sessionID, items)
}

// GCToolSessions mocks base method.
func (m *MockToolSessionIndex) GCToolSessions(tool, branch string, keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GCToolSessions", tool, branch, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// GCToolSessions indicates an expected call of GCToolSessions.
func (mr *MockToolSessionIndexMockRecorder) GCToolSessions(tool, branch, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GCToolSessions", reflect.TypeOf((*MockToolSessionIndex)(nil).GCToolSessions), tool, branch, keep)
}

// GetSeenPaths mocks base method.
func (m *MockToolSessionIndex) GetSeenPaths(sessionID string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeenPaths", sessionID)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeenPaths indicates an expected call of GetSeenPaths.
func (mr *MockToolSessionIndexMockRecorder) GetSeenPaths(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeenPaths", reflect.TypeOf((*MockToolSessionIndex)(nil).GetSeenPaths), sessionID)
}

// GetToolSession mocks base method.
func (m *MockToolSessionIndex) GetToolSession(id string) (*ToolSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolSession", id)
	ret0, _ := ret[0].(*ToolSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToolSession indicates an expected call of GetToolSession.
func (mr *MockToolSessionIndexMockRecorder) GetToolSession(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolSession", reflect.TypeOf((*MockToolSessionIndex)(nil).GetToolSession), id)
}

// QueueSize mocks base method.
func (m *MockToolSessionIndex) QueueSize(sessionID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueSize", sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueSize indicates an expected call of QueueSize.
func (mr *MockToolSessionIndexMockRecorder) QueueSize(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueSize", reflect.TypeOf((*MockToolSessionIndex)(nil).QueueSize), sessionID)
}

// UpdateToolSession mocks base method.
func (m *MockToolSessionIndex) UpdateToolSession(id, lastCommit, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToolSession", id, lastCommit, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateToolSession indicates an expected call of UpdateToolSession.
func (mr *MockToolSessionIndexMockRecorder) UpdateToolSession(id, lastCommit, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToolSession", reflect.TypeOf((*MockToolSessionIndex)(nil).UpdateToolSession), id, lastCommit, status)
}
