// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/detect (interfaces: FactSearcher)
//
// Generated by this command:
//
//	mockgen -destination=internal/detect/mock_fact_searcher_test.go -package=detect knomit/internal/detect FactSearcher
//

// Package detect is a generated GoMock package.
package detect

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFactSearcher is a mock of FactSearcher interface.
type MockFactSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockFactSearcherMockRecorder
	isgomock struct{}
}

// MockFactSearcherMockRecorder is the mock recorder for MockFactSearcher.
type MockFactSearcherMockRecorder struct {
	mock *MockFactSearcher
}

// NewMockFactSearcher creates a new mock instance.
func NewMockFactSearcher(ctrl *gomock.Controller) *MockFactSearcher {
	mock := &MockFactSearcher{ctrl: ctrl}
	mock.recorder = &MockFactSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactSearcher) EXPECT() *MockFactSearcherMockRecorder {
	return m.recorder
}

// NearestFacts mocks base method.
func (m *MockFactSearcher) NearestFacts(vec []float32, k int) ([]SimilarFact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NearestFacts", vec, k)
	ret0, _ := ret[0].([]SimilarFact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NearestFacts indicates an expected call of NearestFacts.
func (mr *MockFactSearcherMockRecorder) NearestFacts(vec, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NearestFacts", reflect.TypeOf((*MockFactSearcher)(nil).NearestFacts), vec, k)
}
