// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/store (interfaces: Embedder)
//
// Generated by this command:
//
//	mockgen -destination=internal/synthesize/mock_embedder_test.go -package=synthesize knomit/internal/store Embedder
//

// Package synthesize is a generated GoMock package.
package synthesize

import (
	context "context"
	"knomit/internal/embeddings/params"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmbedder is a mock of Embedder interface.
type MockEmbedder struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedderMockRecorder
	isgomock struct{}
}

// MockEmbedderMockRecorder is the mock recorder for MockEmbedder.
type MockEmbedderMockRecorder struct {
	mock *MockEmbedder
}

// NewMockEmbedder creates a new mock instance.
func NewMockEmbedder(ctrl *gomock.Controller) *MockEmbedder {
	mock := &MockEmbedder{ctrl: ctrl}
	mock.recorder = &MockEmbedderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedder) EXPECT() *MockEmbedderMockRecorder {
	return m.recorder
}

// Dim mocks base method.
func (m *MockEmbedder) Dim() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dim")
	ret0, _ := ret[0].(int)
	return ret0
}

// Dim indicates an expected call of Dim.
func (mr *MockEmbedderMockRecorder) Dim() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dim", reflect.TypeOf((*MockEmbedder)(nil).Dim))
}

// EmbedDocument mocks base method.
func (m *MockEmbedder) EmbedDocument(ctx context.Context, title, body string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedDocument", ctx, title, body)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedDocument indicates an expected call of EmbedDocument.
func (mr *MockEmbedderMockRecorder) EmbedDocument(ctx, title, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedDocument", reflect.TypeOf((*MockEmbedder)(nil).EmbedDocument), ctx, title, body)
}

// EmbedQuery mocks base method.
func (m *MockEmbedder) EmbedQuery(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedQuery", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedQuery indicates an expected call of EmbedQuery.
func (mr *MockEmbedderMockRecorder) EmbedQuery(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedQuery", reflect.TypeOf((*MockEmbedder)(nil).EmbedQuery), ctx, text)
}

// ID mocks base method.
func (m *MockEmbedder) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockEmbedderMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockEmbedder)(nil).ID))
}

// Thresholds mocks base method.
func (m *MockEmbedder) Thresholds() params.Thresholds {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Thresholds")
	ret0, _ := ret[0].(params.Thresholds)
	return ret0
}

// Thresholds indicates an expected call of Thresholds.
func (mr *MockEmbedderMockRecorder) Thresholds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Thresholds", reflect.TypeOf((*MockEmbedder)(nil).Thresholds))
}
