// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/store (interfaces: SearchIndex)
//
// Generated by this command:
//
//	mockgen -destination=../synthesize/mock_search_index_test.go -package=synthesize knomit/internal/store SearchIndex
//

// Package synthesize is a generated GoMock package.
package synthesize

import (
	context "context"
	store "knomit/internal/store"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchIndex is a mock of SearchIndex interface.
type MockSearchIndex struct {
	ctrl     *gomock.Controller
	recorder *MockSearchIndexMockRecorder
	isgomock struct{}
}

// MockSearchIndexMockRecorder is the mock recorder for MockSearchIndex.
type MockSearchIndexMockRecorder struct {
	mock *MockSearchIndex
}

// NewMockSearchIndex creates a new mock instance.
func NewMockSearchIndex(ctrl *gomock.Controller) *MockSearchIndex {
	mock := &MockSearchIndex{ctrl: ctrl}
	mock.recorder = &MockSearchIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchIndex) EXPECT() *MockSearchIndexMockRecorder {
	return m.recorder
}

// Activity mocks base method.
func (m *MockSearchIndex) Activity(ctx context.Context, branch, path string) (store.ActivityResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activity", ctx, branch, path)
	ret0, _ := ret[0].(store.ActivityResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Activity indicates an expected call of Activity.
func (mr *MockSearchIndexMockRecorder) Activity(ctx, branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activity", reflect.TypeOf((*MockSearchIndex)(nil).Activity), ctx, branch, path)
}

// CachedClusterFacts mocks base method.
func (m *MockSearchIndex) CachedClusterFacts(ctx context.Context, branch string, resolution float64, minCommunitySize int) (store.ClusterResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachedClusterFacts", ctx, branch, resolution, minCommunitySize)
	ret0, _ := ret[0].(store.ClusterResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CachedClusterFacts indicates an expected call of CachedClusterFacts.
func (mr *MockSearchIndexMockRecorder) CachedClusterFacts(ctx, branch, resolution, minCommunitySize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachedClusterFacts", reflect.TypeOf((*MockSearchIndex)(nil).CachedClusterFacts), ctx, branch, resolution, minCommunitySize)
}

// ClusterFacts mocks base method.
func (m *MockSearchIndex) ClusterFacts(ctx context.Context, branch string, resolution float64, minCommunitySize int) (store.ClusterResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterFacts", ctx, branch, resolution, minCommunitySize)
	ret0, _ := ret[0].(store.ClusterResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterFacts indicates an expected call of ClusterFacts.
func (mr *MockSearchIndexMockRecorder) ClusterFacts(ctx, branch, resolution, minCommunitySize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterFacts", reflect.TypeOf((*MockSearchIndex)(nil).ClusterFacts), ctx, branch, resolution, minCommunitySize)
}

// ClusterRefreshInFlight mocks base method.
func (m *MockSearchIndex) ClusterRefreshInFlight(branch string, resolution float64, minCommunitySize int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterRefreshInFlight", branch, resolution, minCommunitySize)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ClusterRefreshInFlight indicates an expected call of ClusterRefreshInFlight.
func (mr *MockSearchIndexMockRecorder) ClusterRefreshInFlight(branch, resolution, minCommunitySize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterRefreshInFlight", reflect.TypeOf((*MockSearchIndex)(nil).ClusterRefreshInFlight), branch, resolution, minCommunitySize)
}

// CommitDetail mocks base method.
func (m *MockSearchIndex) CommitDetail(ctx context.Context, commitHash, pathPrefix string) (*store.CommitDetailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitDetail", ctx, commitHash, pathPrefix)
	ret0, _ := ret[0].(*store.CommitDetailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitDetail indicates an expected call of CommitDetail.
func (mr *MockSearchIndexMockRecorder) CommitDetail(ctx, commitHash, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitDetail", reflect.TypeOf((*MockSearchIndex)(nil).CommitDetail), ctx, commitHash, pathPrefix)
}

// Completions mocks base method.
func (m *MockSearchIndex) Completions(ctx context.Context, branch, category, prefix string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Completions", ctx, branch, category, prefix, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Completions indicates an expected call of Completions.
func (mr *MockSearchIndexMockRecorder) Completions(ctx, branch, category, prefix, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Completions", reflect.TypeOf((*MockSearchIndex)(nil).Completions), ctx, branch, category, prefix, limit)
}

// ExplainFact mocks base method.
func (m *MockSearchIndex) ExplainFact(ctx context.Context, branch, path string) (store.ExplainResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExplainFact", ctx, branch, path)
	ret0, _ := ret[0].(store.ExplainResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExplainFact indicates an expected call of ExplainFact.
func (mr *MockSearchIndexMockRecorder) ExplainFact(ctx, branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExplainFact", reflect.TypeOf((*MockSearchIndex)(nil).ExplainFact), ctx, branch, path)
}

// FactExistsAt mocks base method.
func (m *MockSearchIndex) FactExistsAt(ctx context.Context, branch, path, commit string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FactExistsAt", ctx, branch, path, commit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FactExistsAt indicates an expected call of FactExistsAt.
func (mr *MockSearchIndexMockRecorder) FactExistsAt(ctx, branch, path, commit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FactExistsAt", reflect.TypeOf((*MockSearchIndex)(nil).FactExistsAt), ctx, branch, path, commit)
}

// FactLiveAtCommit mocks base method.
func (m *MockSearchIndex) FactLiveAtCommit(ctx context.Context, branch, path, commit string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FactLiveAtCommit", ctx, branch, path, commit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FactLiveAtCommit indicates an expected call of FactLiveAtCommit.
func (mr *MockSearchIndexMockRecorder) FactLiveAtCommit(ctx, branch, path, commit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FactLiveAtCommit", reflect.TypeOf((*MockSearchIndex)(nil).FactLiveAtCommit), ctx, branch, path, commit)
}

// FactsIter mocks base method.
func (m *MockSearchIndex) FactsIter(ctx context.Context, branch string) (*store.FactsIter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FactsIter", ctx, branch)
	ret0, _ := ret[0].(*store.FactsIter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FactsIter indicates an expected call of FactsIter.
func (mr *MockSearchIndexMockRecorder) FactsIter(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FactsIter", reflect.TypeOf((*MockSearchIndex)(nil).FactsIter), ctx, branch)
}

// GetByPath mocks base method.
func (m *MockSearchIndex) GetByPath(ctx context.Context, branch, path string) (*store.FactWithBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", ctx, branch, path)
	ret0, _ := ret[0].(*store.FactWithBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockSearchIndexMockRecorder) GetByPath(ctx, branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockSearchIndex)(nil).GetByPath), ctx, branch, path)
}

// IncomingAtCommit mocks base method.
func (m *MockSearchIndex) IncomingAtCommit(ctx context.Context, branch, path, commitHash string) ([]store.RefSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncomingAtCommit", ctx, branch, path, commitHash)
	ret0, _ := ret[0].([]store.RefSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncomingAtCommit indicates an expected call of IncomingAtCommit.
func (mr *MockSearchIndexMockRecorder) IncomingAtCommit(ctx, branch, path, commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncomingAtCommit", reflect.TypeOf((*MockSearchIndex)(nil).IncomingAtCommit), ctx, branch, path, commitHash)
}

// LastCommitForPath mocks base method.
func (m *MockSearchIndex) LastCommitForPath(ctx context.Context, branch, path string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastCommitForPath", ctx, branch, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// LastCommitForPath indicates an expected call of LastCommitForPath.
func (mr *MockSearchIndexMockRecorder) LastCommitForPath(ctx, branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastCommitForPath", reflect.TypeOf((*MockSearchIndex)(nil).LastCommitForPath), ctx, branch, path)
}

// Log mocks base method.
func (m *MockSearchIndex) Log(ctx context.Context, branch, path string) ([]store.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, branch, path)
	ret0, _ := ret[0].([]store.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockSearchIndexMockRecorder) Log(ctx, branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockSearchIndex)(nil).Log), ctx, branch, path)
}

// LogPaginated mocks base method.
func (m *MockSearchIndex) LogPaginated(ctx context.Context, branch, path string, limit int, after, from, before string) ([]store.LogEntryWithTags, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogPaginated", ctx, branch, path, limit, after, from, before)
	ret0, _ := ret[0].([]store.LogEntryWithTags)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// LogPaginated indicates an expected call of LogPaginated.
func (mr *MockSearchIndexMockRecorder) LogPaginated(ctx, branch, path, limit, after, from, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogPaginated", reflect.TypeOf((*MockSearchIndex)(nil).LogPaginated), ctx, branch, path, limit, after, from, before)
}

// OutgoingAtCommit mocks base method.
func (m *MockSearchIndex) OutgoingAtCommit(ctx context.Context, branch, path, commitHash string) ([]store.RefSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutgoingAtCommit", ctx, branch, path, commitHash)
	ret0, _ := ret[0].([]store.RefSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutgoingAtCommit indicates an expected call of OutgoingAtCommit.
func (mr *MockSearchIndexMockRecorder) OutgoingAtCommit(ctx, branch, path, commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutgoingAtCommit", reflect.TypeOf((*MockSearchIndex)(nil).OutgoingAtCommit), ctx, branch, path, commitHash)
}

// RecentFacts mocks base method.
func (m *MockSearchIndex) RecentFacts(ctx context.Context, branch string, opts store.SearchOptions) ([]store.RecentFactEntry, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentFacts", ctx, branch, opts)
	ret0, _ := ret[0].([]store.RecentFactEntry)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RecentFacts indicates an expected call of RecentFacts.
func (mr *MockSearchIndexMockRecorder) RecentFacts(ctx, branch, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentFacts", reflect.TypeOf((*MockSearchIndex)(nil).RecentFacts), ctx, branch, opts)
}

// RelevantMethodologyForFact mocks base method.
func (m *MockSearchIndex) RelevantMethodologyForFact(ctx context.Context, branch, factPath string, sourceDomains, sourceEntities []string, k int, minScore float64) ([]store.MethodologyMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelevantMethodologyForFact", ctx, branch, factPath, sourceDomains, sourceEntities, k, minScore)
	ret0, _ := ret[0].([]store.MethodologyMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RelevantMethodologyForFact indicates an expected call of RelevantMethodologyForFact.
func (mr *MockSearchIndexMockRecorder) RelevantMethodologyForFact(ctx, branch, factPath, sourceDomains, sourceEntities, k, minScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelevantMethodologyForFact", reflect.TypeOf((*MockSearchIndex)(nil).RelevantMethodologyForFact), ctx, branch, factPath, sourceDomains, sourceEntities, k, minScore)
}

// RevisionsBefore mocks base method.
func (m *MockSearchIndex) RevisionsBefore(ctx context.Context, branch, path, anchorCommit string, limit int) ([]store.RevisionMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevisionsBefore", ctx, branch, path, anchorCommit, limit)
	ret0, _ := ret[0].([]store.RevisionMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevisionsBefore indicates an expected call of RevisionsBefore.
func (mr *MockSearchIndexMockRecorder) RevisionsBefore(ctx, branch, path, anchorCommit, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevisionsBefore", reflect.TypeOf((*MockSearchIndex)(nil).RevisionsBefore), ctx, branch, path, anchorCommit, limit)
}

// Search mocks base method.
func (m *MockSearchIndex) Search(ctx context.Context, branch string, q store.SearchOptions) ([]store.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, branch, q)
	ret0, _ := ret[0].([]store.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchIndexMockRecorder) Search(ctx, branch, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchIndex)(nil).Search), ctx, branch, q)
}

// Stats mocks base method.
func (m *MockSearchIndex) Stats(ctx context.Context, branch, pathPrefix string) (store.StatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, branch, pathPrefix)
	ret0, _ := ret[0].(store.StatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockSearchIndexMockRecorder) Stats(ctx, branch, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockSearchIndex)(nil).Stats), ctx, branch, pathPrefix)
}

// WalkChangedFiles mocks base method.
func (m *MockSearchIndex) WalkChangedFiles(ctx context.Context, branch, fromCommit, prefix string, seen map[string]bool, limit int) ([]store.FileRecency, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalkChangedFiles", ctx, branch, fromCommit, prefix, seen, limit)
	ret0, _ := ret[0].([]store.FileRecency)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WalkChangedFiles indicates an expected call of WalkChangedFiles.
func (mr *MockSearchIndexMockRecorder) WalkChangedFiles(ctx, branch, fromCommit, prefix, seen, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalkChangedFiles", reflect.TypeOf((*MockSearchIndex)(nil).WalkChangedFiles), ctx, branch, fromCommit, prefix, seen, limit)
}
