// Code generated by MockGen. DO NOT EDIT.
// Source: internal/synthesize/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/synthesize/interfaces.go -destination=internal/synthesize/mock_deps_test.go -package=synthesize
//

// Package synthesize is a generated GoMock package.
package synthesize

import (
	context "context"
	store "knomit/internal/store"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitStore is a mock of GitStore interface.
type MockGitStore struct {
	ctrl     *gomock.Controller
	recorder *MockGitStoreMockRecorder
	isgomock struct{}
}

// MockGitStoreMockRecorder is the mock recorder for MockGitStore.
type MockGitStoreMockRecorder struct {
	mock *MockGitStore
}

// NewMockGitStore creates a new mock instance.
func NewMockGitStore(ctrl *gomock.Controller) *MockGitStore {
	mock := &MockGitStore{ctrl: ctrl}
	mock.recorder = &MockGitStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitStore) EXPECT() *MockGitStoreMockRecorder {
	return m.recorder
}

// BatchWriteFacts mocks base method.
func (m *MockGitStore) BatchWriteFacts(ctx context.Context, branch string, files map[string]string, message, operation string) (string, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchWriteFacts", ctx, branch, files, message, operation)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BatchWriteFacts indicates an expected call of BatchWriteFacts.
func (mr *MockGitStoreMockRecorder) BatchWriteFacts(ctx, branch, files, message, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchWriteFacts", reflect.TypeOf((*MockGitStore)(nil).BatchWriteFacts), ctx, branch, files, message, operation)
}

// DeleteFact mocks base method.
func (m *MockGitStore) DeleteFact(ctx context.Context, branch, path, message string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFact", ctx, branch, path, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFact indicates an expected call of DeleteFact.
func (mr *MockGitStoreMockRecorder) DeleteFact(ctx, branch, path, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFact", reflect.TypeOf((*MockGitStore)(nil).DeleteFact), ctx, branch, path, message)
}

// DiffFiles mocks base method.
func (m *MockGitStore) DiffFiles(ctx context.Context, branch, fromCommit string) ([]string, []string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiffFiles", ctx, branch, fromCommit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].([]string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// DiffFiles indicates an expected call of DiffFiles.
func (mr *MockGitStoreMockRecorder) DiffFiles(ctx, branch, fromCommit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffFiles", reflect.TypeOf((*MockGitStore)(nil).DiffFiles), ctx, branch, fromCommit)
}

// HeadCommit mocks base method.
func (m *MockGitStore) HeadCommit(ctx context.Context, branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadCommit", ctx, branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadCommit indicates an expected call of HeadCommit.
func (mr *MockGitStoreMockRecorder) HeadCommit(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadCommit", reflect.TypeOf((*MockGitStore)(nil).HeadCommit), ctx, branch)
}

// ListAll mocks base method.
func (m *MockGitStore) ListAll(ctx context.Context, branch string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx, branch)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockGitStoreMockRecorder) ListAll(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockGitStore)(nil).ListAll), ctx, branch)
}

// ReadFact mocks base method.
func (m *MockGitStore) ReadFact(ctx context.Context, branch, path string, opts *store.ReadFactOpts) (store.ReadFactResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFact", ctx, branch, path, opts)
	ret0, _ := ret[0].(store.ReadFactResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFact indicates an expected call of ReadFact.
func (mr *MockGitStoreMockRecorder) ReadFact(ctx, branch, path, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFact", reflect.TypeOf((*MockGitStore)(nil).ReadFact), ctx, branch, path, opts)
}

// WriteFact mocks base method.
func (m *MockGitStore) WriteFact(ctx context.Context, branch, path, content, message, operation string) (store.WriteFactResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFact", ctx, branch, path, content, message, operation)
	ret0, _ := ret[0].(store.WriteFactResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteFact indicates an expected call of WriteFact.
func (mr *MockGitStoreMockRecorder) WriteFact(ctx, branch, path, content, message, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFact", reflect.TypeOf((*MockGitStore)(nil).WriteFact), ctx, branch, path, content, message, operation)
}

// MockSearchIndex is a mock of SearchIndex interface.
type MockSearchIndex struct {
	ctrl     *gomock.Controller
	recorder *MockSearchIndexMockRecorder
	isgomock struct{}
}

// MockSearchIndexMockRecorder is the mock recorder for MockSearchIndex.
type MockSearchIndexMockRecorder struct {
	mock *MockSearchIndex
}

// NewMockSearchIndex creates a new mock instance.
func NewMockSearchIndex(ctrl *gomock.Controller) *MockSearchIndex {
	mock := &MockSearchIndex{ctrl: ctrl}
	mock.recorder = &MockSearchIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchIndex) EXPECT() *MockSearchIndexMockRecorder {
	return m.recorder
}

// ClusterFacts mocks base method.
func (m *MockSearchIndex) ClusterFacts(ctx context.Context, branch string, resolution float64, minCommunitySize int) (store.ClusterResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterFacts", ctx, branch, resolution, minCommunitySize)
	ret0, _ := ret[0].(store.ClusterResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterFacts indicates an expected call of ClusterFacts.
func (mr *MockSearchIndexMockRecorder) ClusterFacts(ctx, branch, resolution, minCommunitySize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterFacts", reflect.TypeOf((*MockSearchIndex)(nil).ClusterFacts), ctx, branch, resolution, minCommunitySize)
}

// Delete mocks base method.
func (m *MockSearchIndex) Delete(ctx context.Context, branch, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, branch, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSearchIndexMockRecorder) Delete(ctx, branch, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSearchIndex)(nil).Delete), ctx, branch, path)
}

// Search mocks base method.
func (m *MockSearchIndex) Search(ctx context.Context, branch string, q store.SearchQuery) ([]store.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, branch, q)
	ret0, _ := ret[0].([]store.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchIndexMockRecorder) Search(ctx, branch, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchIndex)(nil).Search), ctx, branch, q)
}

// Upsert mocks base method.
func (m *MockSearchIndex) Upsert(ctx context.Context, branch, commitHash string, r store.FactRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, branch, commitHash, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSearchIndexMockRecorder) Upsert(ctx, branch, commitHash, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSearchIndex)(nil).Upsert), ctx, branch, commitHash, r)
}

// MockEmbedder is a mock of Embedder interface.
type MockEmbedder struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedderMockRecorder
	isgomock struct{}
}

// MockEmbedderMockRecorder is the mock recorder for MockEmbedder.
type MockEmbedderMockRecorder struct {
	mock *MockEmbedder
}

// NewMockEmbedder creates a new mock instance.
func NewMockEmbedder(ctrl *gomock.Controller) *MockEmbedder {
	mock := &MockEmbedder{ctrl: ctrl}
	mock.recorder = &MockEmbedderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedder) EXPECT() *MockEmbedderMockRecorder {
	return m.recorder
}

// Embed mocks base method.
func (m *MockEmbedder) Embed(text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockEmbedderMockRecorder) Embed(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockEmbedder)(nil).Embed), text)
}

// MockBatchEmbedder is a mock of BatchEmbedder interface.
type MockBatchEmbedder struct {
	ctrl     *gomock.Controller
	recorder *MockBatchEmbedderMockRecorder
	isgomock struct{}
}

// MockBatchEmbedderMockRecorder is the mock recorder for MockBatchEmbedder.
type MockBatchEmbedderMockRecorder struct {
	mock *MockBatchEmbedder
}

// NewMockBatchEmbedder creates a new mock instance.
func NewMockBatchEmbedder(ctrl *gomock.Controller) *MockBatchEmbedder {
	mock := &MockBatchEmbedder{ctrl: ctrl}
	mock.recorder = &MockBatchEmbedderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchEmbedder) EXPECT() *MockBatchEmbedderMockRecorder {
	return m.recorder
}

// Embed mocks base method.
func (m *MockBatchEmbedder) Embed(text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockBatchEmbedderMockRecorder) Embed(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockBatchEmbedder)(nil).Embed), text)
}

// EmbedBatch mocks base method.
func (m *MockBatchEmbedder) EmbedBatch(texts []string) ([][]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedBatch", texts)
	ret0, _ := ret[0].([][]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedBatch indicates an expected call of EmbedBatch.
func (mr *MockBatchEmbedderMockRecorder) EmbedBatch(texts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedBatch", reflect.TypeOf((*MockBatchEmbedder)(nil).EmbedBatch), texts)
}
