// Code generated by MockGen. DO NOT EDIT.
// Source: internal/synthesize/review.go
//
// Generated by this command:
//
//	mockgen -source=internal/synthesize/review.go -destination=internal/synthesize/mock_review_idx_test.go -package=synthesize -mock_names=ReviewIndex=MockReviewIndex
//

// Package synthesize is a generated GoMock package.
package synthesize

import (
	store "knomit/internal/store"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReviewIndex is a mock of ReviewIndex interface.
type MockReviewIndex struct {
	ctrl     *gomock.Controller
	recorder *MockReviewIndexMockRecorder
	isgomock struct{}
}

// MockReviewIndexMockRecorder is the mock recorder for MockReviewIndex.
type MockReviewIndexMockRecorder struct {
	mock *MockReviewIndex
}

// NewMockReviewIndex creates a new mock instance.
func NewMockReviewIndex(ctrl *gomock.Controller) *MockReviewIndex {
	mock := &MockReviewIndex{ctrl: ctrl}
	mock.recorder = &MockReviewIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewIndex) EXPECT() *MockReviewIndexMockRecorder {
	return m.recorder
}

// CompleteReviewSession mocks base method.
func (m *MockReviewIndex) CompleteReviewSession(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteReviewSession", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteReviewSession indicates an expected call of CompleteReviewSession.
func (mr *MockReviewIndexMockRecorder) CompleteReviewSession(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteReviewSession", reflect.TypeOf((*MockReviewIndex)(nil).CompleteReviewSession), id)
}

// CreateReviewSession mocks base method.
func (m *MockReviewIndex) CreateReviewSession(branch string) (*store.ReviewSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReviewSession", branch)
	ret0, _ := ret[0].(*store.ReviewSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReviewSession indicates an expected call of CreateReviewSession.
func (mr *MockReviewIndexMockRecorder) CreateReviewSession(branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReviewSession", reflect.TypeOf((*MockReviewIndex)(nil).CreateReviewSession), branch)
}

// GCReviewSessions mocks base method.
func (m *MockReviewIndex) GCReviewSessions(branch string, keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GCReviewSessions", branch, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// GCReviewSessions indicates an expected call of GCReviewSessions.
func (mr *MockReviewIndexMockRecorder) GCReviewSessions(branch, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GCReviewSessions", reflect.TypeOf((*MockReviewIndex)(nil).GCReviewSessions), branch, keep)
}

// GetReviewSession mocks base method.
func (m *MockReviewIndex) GetReviewSession(id string) (*store.ReviewSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewSession", id)
	ret0, _ := ret[0].(*store.ReviewSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewSession indicates an expected call of GetReviewSession.
func (mr *MockReviewIndexMockRecorder) GetReviewSession(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewSession", reflect.TypeOf((*MockReviewIndex)(nil).GetReviewSession), id)
}

// GetReviewWatermark mocks base method.
func (m *MockReviewIndex) GetReviewWatermark(branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewWatermark", branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewWatermark indicates an expected call of GetReviewWatermark.
func (mr *MockReviewIndexMockRecorder) GetReviewWatermark(branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewWatermark", reflect.TypeOf((*MockReviewIndex)(nil).GetReviewWatermark), branch)
}

// InsertWorkItem mocks base method.
func (m *MockReviewIndex) InsertWorkItem(item store.ReviewWorkItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWorkItem", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWorkItem indicates an expected call of InsertWorkItem.
func (mr *MockReviewIndexMockRecorder) InsertWorkItem(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWorkItem", reflect.TypeOf((*MockReviewIndex)(nil).InsertWorkItem), item)
}

// NextWorkItem mocks base method.
func (m *MockReviewIndex) NextWorkItem(sessionID string) (*store.ReviewWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextWorkItem", sessionID)
	ret0, _ := ret[0].(*store.ReviewWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextWorkItem indicates an expected call of NextWorkItem.
func (mr *MockReviewIndexMockRecorder) NextWorkItem(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextWorkItem", reflect.TypeOf((*MockReviewIndex)(nil).NextWorkItem), sessionID)
}

// SetReviewWatermark mocks base method.
func (m *MockReviewIndex) SetReviewWatermark(branch, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReviewWatermark", branch, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReviewWatermark indicates an expected call of SetReviewWatermark.
func (mr *MockReviewIndexMockRecorder) SetReviewWatermark(branch, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReviewWatermark", reflect.TypeOf((*MockReviewIndex)(nil).SetReviewWatermark), branch, hash)
}

// SetWorkItemResponse mocks base method.
func (m *MockReviewIndex) SetWorkItemResponse(id int64, response string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkItemResponse", id, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkItemResponse indicates an expected call of SetWorkItemResponse.
func (mr *MockReviewIndexMockRecorder) SetWorkItemResponse(id, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkItemResponse", reflect.TypeOf((*MockReviewIndex)(nil).SetWorkItemResponse), id, response)
}

// WorkItemStats mocks base method.
func (m *MockReviewIndex) WorkItemStats(sessionID string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkItemStats", sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WorkItemStats indicates an expected call of WorkItemStats.
func (mr *MockReviewIndexMockRecorder) WorkItemStats(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkItemStats", reflect.TypeOf((*MockReviewIndex)(nil).WorkItemStats), sessionID)
}
