// Code generated by MockGen. DO NOT EDIT.
// Source: internal/synthesize/review.go
//
// Generated by this command:
//
//	mockgen -source=internal/synthesize/review.go -destination=internal/synthesize/mock_pipeline_idx_test.go -package=synthesize -mock_names=PipelineIndex=MockPipelineIndex
//

// Package synthesize is a generated GoMock package.
package synthesize

import (
	store "knomit/internal/store"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPipelineIndex is a mock of PipelineIndex interface.
type MockPipelineIndex struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineIndexMockRecorder
	isgomock struct{}
}

// MockPipelineIndexMockRecorder is the mock recorder for MockPipelineIndex.
type MockPipelineIndexMockRecorder struct {
	mock *MockPipelineIndex
}

// NewMockPipelineIndex creates a new mock instance.
func NewMockPipelineIndex(ctrl *gomock.Controller) *MockPipelineIndex {
	mock := &MockPipelineIndex{ctrl: ctrl}
	mock.recorder = &MockPipelineIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineIndex) EXPECT() *MockPipelineIndexMockRecorder {
	return m.recorder
}

// CompletePipelineSession mocks base method.
func (m *MockPipelineIndex) CompletePipelineSession(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompletePipelineSession", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompletePipelineSession indicates an expected call of CompletePipelineSession.
func (mr *MockPipelineIndexMockRecorder) CompletePipelineSession(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompletePipelineSession", reflect.TypeOf((*MockPipelineIndex)(nil).CompletePipelineSession), id)
}

// CreatePipelineSession mocks base method.
func (m *MockPipelineIndex) CreatePipelineSession(tool, branch string) (*store.PipelineSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipelineSession", tool, branch)
	ret0, _ := ret[0].(*store.PipelineSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipelineSession indicates an expected call of CreatePipelineSession.
func (mr *MockPipelineIndexMockRecorder) CreatePipelineSession(tool, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipelineSession", reflect.TypeOf((*MockPipelineIndex)(nil).CreatePipelineSession), tool, branch)
}

// GCPipelineSessions mocks base method.
func (m *MockPipelineIndex) GCPipelineSessions(tool, branch string, keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GCPipelineSessions", tool, branch, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// GCPipelineSessions indicates an expected call of GCPipelineSessions.
func (mr *MockPipelineIndexMockRecorder) GCPipelineSessions(tool, branch, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GCPipelineSessions", reflect.TypeOf((*MockPipelineIndex)(nil).GCPipelineSessions), tool, branch, keep)
}

// GetPipelineSession mocks base method.
func (m *MockPipelineIndex) GetPipelineSession(id string) (*store.PipelineSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineSession", id)
	ret0, _ := ret[0].(*store.PipelineSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineSession indicates an expected call of GetPipelineSession.
func (mr *MockPipelineIndexMockRecorder) GetPipelineSession(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineSession", reflect.TypeOf((*MockPipelineIndex)(nil).GetPipelineSession), id)
}

// GetPipelineWatermark mocks base method.
func (m *MockPipelineIndex) GetPipelineWatermark(tool, branch string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineWatermark", tool, branch)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineWatermark indicates an expected call of GetPipelineWatermark.
func (mr *MockPipelineIndexMockRecorder) GetPipelineWatermark(tool, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineWatermark", reflect.TypeOf((*MockPipelineIndex)(nil).GetPipelineWatermark), tool, branch)
}

// InsertPipelineWorkItem mocks base method.
func (m *MockPipelineIndex) InsertPipelineWorkItem(item store.PipelineWorkItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPipelineWorkItem", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPipelineWorkItem indicates an expected call of InsertPipelineWorkItem.
func (mr *MockPipelineIndexMockRecorder) InsertPipelineWorkItem(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPipelineWorkItem", reflect.TypeOf((*MockPipelineIndex)(nil).InsertPipelineWorkItem), item)
}

// NextPipelineWorkItem mocks base method.
func (m *MockPipelineIndex) NextPipelineWorkItem(sessionID string) (*store.PipelineWorkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPipelineWorkItem", sessionID)
	ret0, _ := ret[0].(*store.PipelineWorkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPipelineWorkItem indicates an expected call of NextPipelineWorkItem.
func (mr *MockPipelineIndexMockRecorder) NextPipelineWorkItem(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPipelineWorkItem", reflect.TypeOf((*MockPipelineIndex)(nil).NextPipelineWorkItem), sessionID)
}

// PipelineWorkItemStats mocks base method.
func (m *MockPipelineIndex) PipelineWorkItemStats(sessionID string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PipelineWorkItemStats", sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PipelineWorkItemStats indicates an expected call of PipelineWorkItemStats.
func (mr *MockPipelineIndexMockRecorder) PipelineWorkItemStats(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PipelineWorkItemStats", reflect.TypeOf((*MockPipelineIndex)(nil).PipelineWorkItemStats), sessionID)
}

// SetPipelineWatermark mocks base method.
func (m *MockPipelineIndex) SetPipelineWatermark(tool, branch, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPipelineWatermark", tool, branch, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPipelineWatermark indicates an expected call of SetPipelineWatermark.
func (mr *MockPipelineIndexMockRecorder) SetPipelineWatermark(tool, branch, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPipelineWatermark", reflect.TypeOf((*MockPipelineIndex)(nil).SetPipelineWatermark), tool, branch, hash)
}

// SetPipelineWorkItemResponse mocks base method.
func (m *MockPipelineIndex) SetPipelineWorkItemResponse(id int64, response string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPipelineWorkItemResponse", id, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPipelineWorkItemResponse indicates an expected call of SetPipelineWorkItemResponse.
func (mr *MockPipelineIndexMockRecorder) SetPipelineWorkItemResponse(id, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPipelineWorkItemResponse", reflect.TypeOf((*MockPipelineIndex)(nil).SetPipelineWorkItemResponse), id, response)
}
