// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/store (interfaces: BatchEmbedder)
//
// Generated by this command:
//
//	mockgen -destination=mock_batch_embedder_test.go -package=store knomit/internal/store BatchEmbedder
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	"knomit/internal/embeddings/params"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBatchEmbedder is a mock of BatchEmbedder interface.
type MockBatchEmbedder struct {
	ctrl     *gomock.Controller
	recorder *MockBatchEmbedderMockRecorder
	isgomock struct{}
}

// MockBatchEmbedderMockRecorder is the mock recorder for MockBatchEmbedder.
type MockBatchEmbedderMockRecorder struct {
	mock *MockBatchEmbedder
}

// NewMockBatchEmbedder creates a new mock instance.
func NewMockBatchEmbedder(ctrl *gomock.Controller) *MockBatchEmbedder {
	mock := &MockBatchEmbedder{ctrl: ctrl}
	mock.recorder = &MockBatchEmbedderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchEmbedder) EXPECT() *MockBatchEmbedderMockRecorder {
	return m.recorder
}

// Dim mocks base method.
func (m *MockBatchEmbedder) Dim() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dim")
	ret0, _ := ret[0].(int)
	return ret0
}

// Dim indicates an expected call of Dim.
func (mr *MockBatchEmbedderMockRecorder) Dim() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dim", reflect.TypeOf((*MockBatchEmbedder)(nil).Dim))
}

// EmbedDocument mocks base method.
func (m *MockBatchEmbedder) EmbedDocument(ctx context.Context, title, body string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedDocument", ctx, title, body)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedDocument indicates an expected call of EmbedDocument.
func (mr *MockBatchEmbedderMockRecorder) EmbedDocument(ctx, title, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedDocument", reflect.TypeOf((*MockBatchEmbedder)(nil).EmbedDocument), ctx, title, body)
}

// EmbedDocuments mocks base method.
func (m *MockBatchEmbedder) EmbedDocuments(ctx context.Context, titles, bodies []string) ([][]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedDocuments", ctx, titles, bodies)
	ret0, _ := ret[0].([][]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedDocuments indicates an expected call of EmbedDocuments.
func (mr *MockBatchEmbedderMockRecorder) EmbedDocuments(ctx, titles, bodies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedDocuments", reflect.TypeOf((*MockBatchEmbedder)(nil).EmbedDocuments), ctx, titles, bodies)
}

// EmbedShortStrings mocks base method.
func (m *MockBatchEmbedder) EmbedShortStrings(ctx context.Context, texts []string) ([][]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedShortStrings", ctx, texts)
	ret0, _ := ret[0].([][]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedShortStrings indicates an expected call of EmbedShortStrings.
func (mr *MockBatchEmbedderMockRecorder) EmbedShortStrings(ctx, texts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedShortStrings", reflect.TypeOf((*MockBatchEmbedder)(nil).EmbedShortStrings), ctx, texts)
}

// EmbedQuery mocks base method.
func (m *MockBatchEmbedder) EmbedQuery(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmbedQuery", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmbedQuery indicates an expected call of EmbedQuery.
func (mr *MockBatchEmbedderMockRecorder) EmbedQuery(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmbedQuery", reflect.TypeOf((*MockBatchEmbedder)(nil).EmbedQuery), ctx, text)
}

// ID mocks base method.
func (m *MockBatchEmbedder) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockBatchEmbedderMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockBatchEmbedder)(nil).ID))
}

// Thresholds mocks base method.
func (m *MockBatchEmbedder) Thresholds() params.Thresholds {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Thresholds")
	ret0, _ := ret[0].(params.Thresholds)
	return ret0
}

// Thresholds indicates an expected call of Thresholds.
func (mr *MockBatchEmbedderMockRecorder) Thresholds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Thresholds", reflect.TypeOf((*MockBatchEmbedder)(nil).Thresholds))
}
