// Code generated by MockGen. DO NOT EDIT.
// Source: knomit/internal/llm (interfaces: LLMAdapter)
//
// Generated by this command:
//
//	mockgen -destination=internal/llm/mock_adapter_test.go -package=llm knomit/internal/llm LLMAdapter
//

// Package llm is a generated GoMock package.
package llm

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLLMAdapter is a mock of LLMAdapter interface.
type MockLLMAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockLLMAdapterMockRecorder
	isgomock struct{}
}

// MockLLMAdapterMockRecorder is the mock recorder for MockLLMAdapter.
type MockLLMAdapterMockRecorder struct {
	mock *MockLLMAdapter
}

// NewMockLLMAdapter creates a new mock instance.
func NewMockLLMAdapter(ctrl *gomock.Controller) *MockLLMAdapter {
	mock := &MockLLMAdapter{ctrl: ctrl}
	mock.recorder = &MockLLMAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMAdapter) EXPECT() *MockLLMAdapterMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockLLMAdapter) Complete(ctx context.Context, system string, msgs []Message, onChunk func(string)) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, system, msgs, onChunk)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockLLMAdapterMockRecorder) Complete(ctx, system, msgs, onChunk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockLLMAdapter)(nil).Complete), ctx, system, msgs, onChunk)
}
